nohup: ignoring input
Watching for file changes with StatReloader
Internal Server Error: /api/categories/
Traceback (most recent call last):
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 715, in to_representation
    return [
           ^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 716, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 525, in to_representation
    for field in fields:
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `icon` is not valid for model `Category` in `batteries.serializers.CategorySerializer`.
[29/Aug/2025 11:28:54] "GET /api/categories/ HTTP/1.1" 500 160236
Internal Server Error: /api/categories/
Traceback (most recent call last):
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 715, in to_representation
    return [
           ^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 716, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 525, in to_representation
    for field in fields:
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `icon` is not valid for model `Category` in `batteries.serializers.CategorySerializer`.
[29/Aug/2025 11:29:49] "GET /api/categories/ HTTP/1.1" 500 23146
/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/batteries/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 29, 2025 - 11:27:29
Django version 5.2.5, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
[29/Aug/2025 11:30:25] "GET /api/categories/ HTTP/1.1" 200 2296
[29/Aug/2025 11:30:47] "GET /api/categories/?category_type=vehicle_type HTTP/1.1" 200 2323
[29/Aug/2025 11:31:24] "GET /api/categories/?type=vehicle_type HTTP/1.1" 200 968
[29/Aug/2025 11:33:29] "GET /api/batteries/ HTTP/1.1" 200 7965
[29/Aug/2025 11:33:43] "GET /api/batteries/?vehicle_search=Toyota+Corolla HTTP/1.1" 200 52
[29/Aug/2025 11:34:32] "GET /api/batteries/?categories=17 HTTP/1.1" 200 7965
/home/hinatahyuga/Documents/Side Projects/Exact-Match/exactmatch-backend/batteries/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 29, 2025 - 11:30:15
Django version 5.2.5, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Watching for file changes with StatReloader
[29/Aug/2025 11:35:52] "GET /api/batteries/?categories=17 HTTP/1.1" 200 1458
